#!/usr/bin/env python3
"""Build a deterministic, self-contained CILS LaTeX source archive.

The archive contains only publication sources, the generated Supporting
Information tables, and the six vector main figures. It intentionally excludes
auxiliary LaTeX files, PNG previews, model artifacts, and row-level data.

Elsevier Editorial Manager cannot process LaTeX submissions with subfolders,
so every archive member is deliberately written at the ZIP root. The packaged
copy of ``main.tex`` is rewritten to use those flat paths; the repository source
retains its more maintainable directory structure.
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path
import tempfile
import zipfile


SCRIPT_DIR = Path(__file__).resolve().parent
LATEX_DIR = SCRIPT_DIR.parent
REPO_ROOT = LATEX_DIR.parent
FIGURE_DIR = (
    REPO_ROOT
    / "paper2_admet_benchmark"
    / "results"
    / "manuscript_assets"
    / "figures"
)
OUTPUT = SCRIPT_DIR / "CILS_Paper2_TAME_LaTeX_Source.zip"
ZIP_TIMESTAMP = (2026, 8, 13, 0, 0, 0)

FIGURE_STEMS = (
    "figure_1_evidence_chain",
    "figure_2_shift_performance",
    "figure_3_reliability_illusion",
    "figure_4_domain_retention",
    "figure_5_tame_mechanism",
    "figure_6_epa_validation",
)


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def source_map() -> dict[str, Path]:
    files = {
        "main.tex": LATEX_DIR / "main.tex",
        "main.bbl": LATEX_DIR / "main.bbl",
        "supplementary.tex": LATEX_DIR / "supplementary.tex",
        "generated_supplementary_tables.tex": LATEX_DIR
        / "generated_supplementary_tables.tex",
        "statements.tex": LATEX_DIR / "statements.tex",
        "references.bib": LATEX_DIR / "references.bib",
        "references_2026.bib": LATEX_DIR / "references_2026.bib",
    }
    for name in ("abstract", "introduction", "methods", "results", "discussion"):
        files[f"{name}.tex"] = LATEX_DIR / "sections" / f"{name}.tex"
    for stem in FIGURE_STEMS:
        files[f"{stem}.pdf"] = FIGURE_DIR / f"{stem}.pdf"
    return files


def flattened_main_bytes() -> bytes:
    """Return the submission copy of main.tex with root-level dependencies."""

    text = (LATEX_DIR / "main.tex").read_text(encoding="utf-8")
    text = text.replace(
        "\\graphicspath{{figures/}{../paper2_admet_benchmark/results/manuscript_assets/figures/}}",
        "\\graphicspath{{./}}",
    )
    for name in ("abstract", "introduction", "methods", "results", "discussion"):
        text = text.replace(f"\\input{{sections/{name}}}", f"\\input{{{name}}}")
    forbidden = ("sections/", "figures/", "../paper2_admet_benchmark/")
    leftovers = [token for token in forbidden if token in text]
    if leftovers:
        raise RuntimeError(f"Flat main.tex still contains directory paths: {leftovers}")
    return text.encode("utf-8")


def readme_bytes() -> bytes:
    text = """CILS Paper 2 - self-contained LaTeX source package

Manuscript: main.tex
Supporting Information: supplementary.tex
Authors: Siyuan Tong and Yuechen Wang

All TeX, BibTeX, and figure files are at the ZIP root, as required by Elsevier
Editorial Manager. The archive compiles independently of the research repository.

Suggested build commands:
  latexmk -pdf -bibtex -interaction=nonstopmode -file-line-error -halt-on-error main.tex
  latexmk -pdf -interaction=nonstopmode -file-line-error -halt-on-error supplementary.tex

MANIFEST_SHA256.txt records the SHA-256 digest and byte size of every included
source file. Auxiliary files and PDFs generated by LaTeX are intentionally not
included in this source archive.
"""
    return text.encode("utf-8")


def zip_info(name: str) -> zipfile.ZipInfo:
    info = zipfile.ZipInfo(name, ZIP_TIMESTAMP)
    info.compress_type = zipfile.ZIP_DEFLATED
    info.external_attr = 0o100644 << 16
    info.create_system = 3
    return info


def build() -> Path:
    sources = source_map()
    missing = [str(path) for path in sources.values() if not path.is_file()]
    if missing:
        raise FileNotFoundError(
            "Submission inputs are missing. Rebuild the manuscript and Supporting "
            "Information before packaging:\n" + "\n".join(missing)
        )

    payloads = {name: path.read_bytes() for name, path in sources.items()}
    payloads["main.tex"] = flattened_main_bytes()
    payloads["README_SUBMISSION.txt"] = readme_bytes()
    nested = sorted(name for name in payloads if "/" in name or "\\" in name)
    if nested:
        raise RuntimeError(f"Editorial Manager archive contains subfolders: {nested}")
    manifest = ["sha256  bytes  file"]
    for name in sorted(payloads):
        data = payloads[name]
        manifest.append(f"{sha256_bytes(data)}  {len(data)}  {name}")
    payloads["MANIFEST_SHA256.txt"] = ("\n".join(manifest) + "\n").encode("utf-8")

    with tempfile.NamedTemporaryFile(
        mode="wb", suffix=".zip", prefix="cils-paper2-", dir=SCRIPT_DIR, delete=False
    ) as handle:
        temporary = Path(handle.name)

    try:
        with zipfile.ZipFile(temporary, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            for name in sorted(payloads):
                archive.writestr(zip_info(name), payloads[name])

        with zipfile.ZipFile(temporary, "r") as archive:
            corrupt = archive.testzip()
            if corrupt is not None:
                raise RuntimeError(f"Corrupt member in submission archive: {corrupt}")
            observed = set(archive.namelist())
            expected = set(payloads)
            if observed != expected:
                raise RuntimeError(
                    f"Archive member mismatch: missing={sorted(expected - observed)}, "
                    f"extra={sorted(observed - expected)}"
                )
            for name, expected_bytes in payloads.items():
                if archive.read(name) != expected_bytes:
                    raise RuntimeError(f"Archive byte mismatch: {name}")

        os.replace(temporary, OUTPUT)
    finally:
        temporary.unlink(missing_ok=True)

    print(f"wrote {OUTPUT}")
    print(f"bytes {OUTPUT.stat().st_size}")
    print(f"sha256 {sha256_bytes(OUTPUT.read_bytes())}")
    return OUTPUT


if __name__ == "__main__":
    build()
